config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'api/news'
  get 'api/:date1/:date2', to: 'api#by_date'
  post 'api/create', to: 'api#create'

        
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :tweets
  
  put 'tweet/:id/like', to: 'tweets#like', as: 'like'
  delete 'tweet/:id/dislike', to: 'tweets#dislike', as: 'dislike'

  post 'tweet/:id/retweet', to: 'tweets#retweet', as: 'retweet'

  get 'tweets/search/:search', to: 'tweets#search', as: 'search'


  get 'home/profile', to: 'home#profile'
  get 'home/tweets', to: 'home#tweets'
  post 'home/:id/follow', to: "home#follow", as: "follow_user"
  delete 'home/:id/unfollow', to: "home#unfollow", as: "unfollow_user"



  root to: "tweets#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  belongs_to :tweet, class_name: 'Tweet', optional: true
  has_many :tweets, foreign_key: :tweet_id, class_name: 'Tweet', dependent: :destroy
  validates :content, presence: true

  def liked?(user)
    !!self.likes.find{|like| like.user_id == user.id}
  end

  def likes_count
    self.likes.count
  end

  def rt_count
    self.tweets.count
  end

  def self.search(search)
    if search
      where('content LIKE ?', "%#{search}%" || "%#{search}" || "#{search}%" )
    else
      all
    end
  end

  def self.hashtag_search(search)
    if search
      where('content LIKE ?', "%##{search}%" )
    else
      all
    end
  end
  
 scope :tweets_for_me, ->(followings) { where user_id: followings }
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, except: [:index, :new, :create, :search]
  before_action :authenticate_user!, except: [:index, :show]

  def like
    Like.create(user_id: current_user.id, tweet_id: @tweet.id)
    redirect_to root_path
  end

  def dislike
    Like.find_by(user_id: current_user.id, tweet_id: @tweet.id).destroy
    redirect_to root_path
  end

  def retweet
    @retweet = Tweet.create(user_id: current_user.id, tweet_id: @tweet.id, content: @tweet.content)

    respond_to do |format|
      if @retweet.save
        format.html { redirect_to root_path, notice: 'Tweet was successfully created.' }
      else
        format.html { render :index }
      end
    end
  end

  def index
    if user_signed_in?
      @tweets = Tweet.tweets_for_me(current_user.followings).search(params[:search]).order('created_at DESC').page(params[:page]).per(50)
    else 
      @tweets = Tweet.search(params[:search]).order('created_at DESC').page(params[:page]).per(50)
    end

    @tweet = Tweet.new
    
  end

  def search
    if user_signed_in?
      @tweets = Tweet.tweets_for_me(current_user.followings).hashtag_search(params[:search]).order('created_at DESC').page(params[:page]).per(50)
    else 
      @tweets = Tweet.hashtag_search(params[:search]).order('created_at DESC').page(params[:page]).per(50)
    end
  end

  def show
    @retweet = Tweet.find_by(id: @tweet.tweet_id)
  end

  def new
    @tweet = Tweet.new
  end

  def edit
  end

  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: 'Tweet was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
    end
  end

  private

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def tweet_params
    params.require(:tweet).permit(:content, :user_id, :tweet_id)
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
    def render_hashtag(content)
        content.gsub(/#\w+/) { |w| link_to w, "tweets/search/#{w.delete('#')}" }.html_safe
    end
end

app/views/tweets/_form.html.erb
<%= form_with model: @tweet, local: true do |form| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :content %>
    <%= form.text_area :content, id: :tweet_content, class: "form-control col-6", rows: "3" %>
  </div>

  <% if current_user %>
    <%= form.hidden_field :user_id, value:current_user.id %>
  <% end %>

  <div class="actions">
    <%= form.submit class: "btn btn-light btn-outline-info mt-3 mb-5" %>
  </div>
<% end %>

app/views/tweets/_sidebar.html.erb
<nav id="sidebar" class="bg-light text-dark">
    <div class="pt-5 pl-4">
        <h3>Users</h3>
    </div>

    <ul class="list-unstyled pl-4 mt-4">
        <% User.all.each do |user| %>
        <div class="row container">
            <li>
                <% if user.username? %>
                    <%= user %>
                <% else %>
                    <%= "jane doe" %>
                <% end %>

                <% if current_user.followed?(user) %>
                    <%= link_to 'Follow', follow_user_path(user), method: "post", class: "btn btn-info btn-sm m-2" %>
                <% else %>
                    <%= link_to 'Unfollow', unfollow_user_path(user), method: "delete", class: "btn btn-info btn-sm" %>
                <% end %>
            </li>
        </div>
        
        <% end %>
    </ul>
</nav>

app/views/tweets/_tweets.html.erb
<%= paginate @tweets %>

<div class="row mb-3 mt-3">
  <% @tweets.each do |tweet| %>
    <div class="col-sm-6 col-md-4 card-deck">
      <div class="card mt-2">
          <div class="card-body">

            <!-- contenido -->
            <h5 class="card-title"><%= render_hashtag(tweet.content) %></h5>
            <p class="card-text">

              <!-- Foto usuario  -->
              <%= link_to(image_tag(tweet.user.photo, class: "img-fluid rounded d-inline-block w-25"), tweet) if tweet.user.photo? %>
              <%= tweet.user %>
            </p>

            <!-- Fecha -->
            <p class="card-text">
              <%= link_to tweet_path(tweet) do %>
                <small class="text-dark"><%= time_ago_in_words(tweet.created_at) %> ago</small>
              <% end %>
            </p>
            
            <div class="row">
              <div class="col-6 mb-3">
                <p class="card-text">
                  
                  <!-- Boton Like -->
                  
                  <% if user_signed_in? %>
                    <% if tweet.liked?(current_user) %>
                      <%= link_to "Dislike", dislike_path(tweet), method: "delete", class: "btn btn-danger btn-sm" %>
                    <% else %>
                      <%= link_to "Like", like_path(tweet), method: "put", class: "btn btn-danger btn-sm" %>
                    <% end %>
                  <% end %>
  
                  <!-- Boton RT -->
                  <% if user_signed_in? %>
                    <%= link_to "RT", retweet_path(tweet), method: "post", class: "btn btn-info btn-sm" %>
                  <% end %>
              </p>
              </div>
              <div class="col-6">
                <small class="text-danger"><%= tweet.likes_count %> likes</small>
                <small class="text-info"><%= tweet.rt_count %> retweets</small>
              </div>
            </div>
            
            <!-- Botones show, edit, destroy -->

            <p>
              <%= link_to 'Show', tweet, class: "btn btn-outline-info btn-sm" %> 
              <% if user_signed_in? && tweet.user_id == current_user.id %>
                <%= link_to 'Edit', edit_tweet_path(tweet), class: "btn btn-outline-dark btn-sm" %> 
              <%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-warning btn-sm" %>
              <% end %>
              
            </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= paginate @tweets %>

app/views/tweets/edit.html.erb
<div class="container mt-5">
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<p><%= link_to 'Show', @tweet, class: "btn btn-outline-info mt-3" %></p>
<p><%= link_to 'Back', tweets_path, class: "btn btn-dark mt-3" %></p>
</div>

app/views/tweets/index.html.erb
<div class="wrapper">
<% if user_signed_in? %>
  <%= render 'sidebar' %>
<% end %>

<div class="container pt-5">


<div class="row mb-3">
  <div class="col-xs-8 col-sm-8">
    <h1>Tweets</h1>
  </div>
  <div class="col-sm-4">
    <%= link_to 'Admin', new_admin_user_session_path, class: "btn btn-info btn-sm" %>
    <p>email: admin@example.com</p>
    <p>pass: password</p>
  </div>

  <% if user_signed_in? %>
    <div class="col-xs-8 col-sm-10 mt-3 ">
      <h3>New Tweet</h3>
    </div>
  <% end %>
</div>

<% if user_signed_in? %>
  <%= render 'form' %>
<% end %>

<%= form_tag tweets_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search], class: "form mr-sm-2" %>
    <%= submit_tag "Buscar", class: "btn btn-sm btn-light btn-outline-info ml-2" %>
  </p>
<% end %>

<%= render 'tweets' %>

  <br>
  
</div>

</div>

app/views/tweets/new.html.erb
<div class="container mt-5">
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path, class: "btn btn-dark mt-3" %>
</div>

app/views/tweets/search.html.erb
<div class="container mt-5 mr-5">


<div class="row mb-3">
    <div class="col-xs-6 col-sm-6">
      <h1>Tweets</h1>
    </div>
    <div>
        <%= link_to 'Back', root_path, class: "btn btn-outline-info" %>
    </div>
    

    <%= paginate @tweets %>
  
    <div class="row mb-3 mt-3">
      <% @tweets.each do |tweet| %>
      <div class="row row-cols-1 row-cols-md-3 ">
        <div class="col mb-4">
          <div class="card h-100 mt-5">
            <div class="card-body">

                <!-- contenido -->

                <h5 class="card-title"><%= tweet.content %></h5>
                <p class="card-text">

                <!-- Foto usuario  -->
                
                    <%= link_to(image_tag(tweet.user.photo, class: "img-fluid rounded d-inline-block w-25"), tweet) if tweet.user.photo? %>
                    <%= tweet.user %>
                </p>

                <!-- Fecha -->
                
                <p class="card-text">
                    <%= link_to tweet_path(tweet) do %>
                        <small class="text-dark"><%= time_ago_in_words(tweet.created_at) %> ago</small>
                    <% end %>
                </p>
                
                <div class="row">
                <div class="col-6 mb-3">
                    <p class="card-text">
                    
                    <!-- Boton Like -->
                    
                        <% if user_signed_in? %>
                            <% if tweet.liked?(current_user) %>
                            <%= link_to "Dislike", dislike_path(tweet), method: "delete", class: "btn btn-danger btn-sm" %>
                            <% else %>
                            <%= link_to "Like", like_path(tweet), method: "put", class: "btn btn-danger btn-sm" %>
                            <% end %>
                        <% end %>
        
                        <!-- Boton RT -->

                        <% if user_signed_in? %>
                            <%= link_to "RT", retweet_path(tweet), method: "post", class: "btn btn-info btn-sm" %>
                        <% end %>
                    </p>
                </div>
                    <div class="col-6">
                        <small class="text-danger"><%= tweet.likes_count %> likes</small>
                        <small class="text-info"><%= tweet.rt_count %> retweets</small>
                    </div>
                </div>
                
                <!-- Botones show, edit, destroy -->

                <p>
                    <%= link_to 'Show', tweet, class: "btn btn-outline-info btn-sm" %> 
                    <% if user_signed_in? && tweet.user_id == current_user.id %>
                        <%= link_to 'Edit', edit_tweet_path(tweet), class: "btn btn-outline-dark btn-sm" %> 
                    <%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-warning btn-sm" %>
                    <% end %>
                
                </p>
            </div>
        </div>
        </div>
      </div>
      <% end %>
    </div>

<%= paginate @tweets %>

  <br>
  
</div>
    

app/views/tweets/show.html.erb
<div class="container mt-5">
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          <h1><%= @tweet.content %></h1>
        </div>
        <div class="col-md-2"></div>
    </div>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          <h4>Twiteado por <%= @tweet.user %> </h4>
          <% if @tweet.user.photo != nil %>
            <div class="col-md-4">
              <p><%= link_to(image_tag(@tweet.user.photo, class:"rounded-circle w-25")) %></p>
            </div>
          <% end %>


          <% if @tweet.tweet_id != nil %>
            <h4>Original de <%= @retweet.user %></h4>       
          <% end %>

          <small><%= time_ago_in_words(@tweet.created_at) %> ago</small>
        </div>
        <div class="col-md-2"></div>
    </div>
      
    <br>

    <div class="row">
      <div class="col-md-2"></div> 
      <div class="col-md-4">
        <% if user_signed_in? %>
          <% if @tweet.liked?(current_user) %>
            <%= link_to "Dislike", dislike_path(@tweet), method: "delete", class: "btn btn-danger btn-sm" %>
          <% else %>
            <%= link_to "Like", like_path(@tweet), method: "put", class: "btn btn-danger btn-sm" %>
          <% end %>
        <% end %>

        <% if user_signed_in? %>
          <%= link_to "RT", retweet_path(@tweet), method: "post", class: "btn btn-info btn-sm" %>
        <% end %>
        
        <small class="text-danger"><%= @tweet.likes_count %> likes</small>
        <small class="text-info"><%= @tweet.rt_count %> retweets</small>
      </div>
      <div class="col-md-4">
          <p>
            
            <% if user_signed_in? && @tweet.user_id == current_user.id %>
              <%= link_to 'Edit', edit_tweet_path(@tweet), class: "btn btn-outline-dark btn-sm" %> 
              <%= link_to 'Destroy', tweet_path(@tweet), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-warning btn-sm" %>
            <% end %>
            <%= link_to 'Back', tweets_path, class: "btn btn-outline-info btn-sm" %>
            </p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-2">
        <p> Likes de: 
          <% @tweet.likes.each do |like| %>
          <%= link_to(image_tag(like.user.photo, class: "img-fluid rounded-circle w-25")) if like.user.photo? %>
          <% end %>
        </p>
      </div>
      <div class="col-md-2"></div>
    </div>

</div>
</div>