config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'api/news'
  get 'api/:date1/:date2', to: 'api#by_date'
  post 'api/create', to: 'api#create'

        
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :tweets
  
  put 'tweet/:id/like', to: 'tweets#like', as: 'like'
  delete 'tweet/:id/dislike', to: 'tweets#dislike', as: 'dislike'

  post 'tweet/:id/retweet', to: 'tweets#retweet', as: 'retweet'

  get 'tweets/search/:search', to: 'tweets#search', as: 'search'


  get 'home/profile', to: 'home#profile'
  get 'home/tweets', to: 'home#tweets'
  post 'home/:id/follow', to: "home#follow", as: "follow_user"
  delete 'home/:id/unfollow', to: "home#unfollow", as: "unfollow_user"



  root to: "tweets#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-info">
  <div class="container-fluid">
    <%= link_to 'Trinitter', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <%= link_to 'Home', root_path, class: "nav-link" %>
        </li>
      </ul>
        <ul class="navbar-nav navbar-right" >
          <% if user_signed_in? %>
            <li class="nav-item"><%= link_to 'My Profile', home_profile_path , class: "nav-link" %></li>
            <li role="separator" class="divider"></li>
            <li class="nav-item"><%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "nav-link" %></li>
        <% else %>
            <li class="nav-item"><%= link_to 'Log in', user_session_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %></li>
      <% end  %>
        </ul>

    </div>
  </div>
</nav>