config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'api/news'
  get 'api/:date1/:date2', to: 'api#by_date'
  post 'api/create', to: 'api#create'

        
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :tweets
  
  put 'tweet/:id/like', to: 'tweets#like', as: 'like'
  delete 'tweet/:id/dislike', to: 'tweets#dislike', as: 'dislike'

  post 'tweet/:id/retweet', to: 'tweets#retweet', as: 'retweet'

  get 'tweets/search/:search', to: 'tweets#search', as: 'search'


  get 'home/profile', to: 'home#profile'
  get 'home/tweets', to: 'home#tweets'
  post 'home/:id/follow', to: "home#follow", as: "follow_user"
  delete 'home/:id/unfollow', to: "home#unfollow", as: "unfollow_user"



  root to: "tweets#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def profile
    @user = current_user
  end

  def tweets
    @tweets = current_user.tweets.order('created_at DESC').page(params[:page]).per(50)
  end

  def follow
    @user = User.find(params[:id])
    current_user.followings << @user
    redirect_to root_path
  end

  def unfollow
    @user = User.find(params[:id])
    current_user.given_follows.find_by(followed_user_id: @user.id).destroy
    redirect_to root_path
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/profile.html.erb
<div class="container mt-5">
<h1 class="mb-5">My Profile</h1>

<%= link_to(image_tag(@user.photo, class: "img-fluid rounded d-inline-block w-25")) if @user.photo? %>

<h3 class="mb-3">
  <strong>Username:</strong>
  <%= @user %>
</h3>

<h3 class="mb-3">
  <strong>Email:</strong>
  <%= @user.email %>
</h3>

<%= link_to 'Back', root_path, class: "btn btn-dark" %>

</div>

app/views/home/tweets.html.erb
<div class="container mt-5">

<div class="row mb-3">
    <div class="col-xs-8 col-sm-10">
      <h1>Tweets</h1>
    </div>
    <div class="col-xs-4 col-sm-2">
      <%= link_to 'New tweet', new_tweet_path, class: "btn btn-info btn-sm" %>
    </div>
</div>

<%= paginate @tweets %>
  
<div class="row mb-3 mt-3">
  <% @tweets.each do |tweet| %>
    <div class="col-sm-6 col-md-4 card-deck">
      <div class="card mt-2">
          <div class="card-body">
            <h5 class="card-title"><%= tweet.content %></h5>
            <p class="card-text">
              <%= link_to(image_tag(tweet.user.photo, class: "img-fluid rounded d-inline-block w-25"), tweet) if tweet.user.photo? %>
              <%= tweet.user %>
            </p>
            <p class="card-text">
              <%= link_to tweet_path(tweet) do %>
                <small class="text-dark"><%= time_ago_in_words(tweet.created_at) %> ago</small>
              <% end %>
            </p>
            
            <div class="row">
              <div class="col-6 mb-3">
                <p class="card-text">
                  <% if user_signed_in? %>
                    <% if tweet.liked?(current_user) %>
                      <%= link_to "Dislike", dislike_path(tweet), method: "delete", class: "btn btn-danger btn-sm" %>
                    <% else %>
                      <%= link_to "Like", like_path(tweet), method: "put", class: "btn btn-danger btn-sm" %>
                    <% end %>
                  <% end %>
  
  
                  <% if user_signed_in? %>
                    <%= link_to "RT", retweet_path(tweet), method: "post", class: "btn btn-info btn-sm" %>
                  <% end %>
              </p>
              </div>
              <div class="col-6">
                <small class="text-danger"><%= tweet.likes_count %> likes</small>
                <small class="text-info"><%= tweet.rt_count %> retweets</small>
              </div>
            </div>
            



            <p>
              <%= link_to 'Show', tweet, class: "btn btn-outline-info btn-sm" %> 
              <% if user_signed_in? && tweet.user_id == current_user.id %>
                <%= link_to 'Edit', edit_tweet_path(tweet), class: "btn btn-outline-dark btn-sm" %> 
              <%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-warning btn-sm" %>
              <% end %>
              
            </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= paginate @tweets %>


  <br>

</div>